info:
  contact: {}
paths:
  /login:
    post:
      operationId: Post
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
      summary: Login on app
swagger: "2.0"
